CREATE TABLE analysis_session (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at        TIMESTAMP WITH TIME ZONE,
    client_label    VARCHAR(120),
    source_type     VARCHAR(16) NOT NULL,
    CONSTRAINT chk_analysis_session_source_type
        CHECK (source_type IN ('WEBCAM', 'UPLOAD', 'MOCK'))
);

CREATE TABLE frame (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id          BIGINT NOT NULL REFERENCES analysis_session (id) ON DELETE CASCADE,
    sequence_no         INT NOT NULL,
    captured_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    latency_ms          INT,
    crowd_density       VARCHAR(8) NOT NULL,
    max_proximity_risk  VARCHAR(8) NOT NULL,
    recommendation      VARCHAR(8) NOT NULL,
    person_count        INT NOT NULL,
    CONSTRAINT uq_frame_session_sequence UNIQUE (session_id, sequence_no),
    CONSTRAINT chk_frame_crowd_density
        CHECK (crowd_density IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT chk_frame_max_proximity_risk
        CHECK (max_proximity_risk IN ('SAFE', 'WARNING', 'DANGER')),
    CONSTRAINT chk_frame_recommendation
        CHECK (recommendation IN ('PROCEED', 'CAUTION', 'STOP'))
);

CREATE INDEX idx_frame_session_id ON frame (session_id);
CREATE INDEX idx_frame_captured_at ON frame (captured_at);

CREATE TABLE detection (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    frame_id        BIGINT NOT NULL REFERENCES frame (id) ON DELETE CASCADE,
    class_label     VARCHAR(16) NOT NULL,
    confidence      NUMERIC(5, 4) NOT NULL,
    x_center        NUMERIC(6, 4) NOT NULL,
    y_center        NUMERIC(6, 4) NOT NULL,
    width           NUMERIC(6, 4) NOT NULL,
    height          NUMERIC(6, 4) NOT NULL,
    proximity_risk  VARCHAR(8),
    CONSTRAINT chk_detection_class_label
        CHECK (class_label IN ('person', 'wheelchair', 'luggage')),
    CONSTRAINT chk_detection_proximity_risk
        CHECK (proximity_risk IS NULL OR proximity_risk IN ('SAFE', 'WARNING', 'DANGER'))
);

CREATE INDEX idx_detection_frame_id ON detection (frame_id);
CREATE INDEX idx_detection_class_label ON detection (class_label);
